#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Mon Jun  3 15:06:22 CST 2019
#define FWConfiguration SGRhyOAEblIlBKjv
#define fwDidFinishLaunchingWithOptions zYXkspLVcaCqkSHz
#define fwJpushDidReceiveNotificationResponse xwcGdzqaRAeFIviT
#define fwRunOnHomeViewControllerBecomeActive TSUvMawbRUghmpqT
#define fwLanguage XoxQJiqELPQhkRvy
#define urlString JEPoMfmpTiowneWn
#define weakSelf lMBecdUqvVQiKbxE
#define lcStatus LhnTLQOYdspzLQTg
#define lcUrlString xRImvtLhPubdemUq
#define AdvertistingObject WhRRdJTsRKiNQnzz
#define adWebView GfvcoRosThubQBhl
#define AD_DURATION ANQfCliiaAtbiZoP
#define showAdvertistingView jfKNOBWLQPjmxOiY
#define removeAdvertistingView QpmZjiJMqfDhFfVt
#define trimURL AGYEQwiOBiRNxjNm
#define sourceString LTfhBuclyqBuNeJl
#define isChinaArea tfeuvabRLlPFBWIt
#define leftConstraint asfLCxaVKoOdkasG
#define rightConstraint wDiIxBockOInTHBY
#define topConstraint toBQAQsfDyFgBNaR
#define bottomConstraint iuLYxLGkypANJcMr
#define rmSuperview dssrysICPuWOpuBy
#define destinationString NjxKVSQLikNbWAXQ
#define isLanguage DldaIYvvhXVaCmJl
#define leanCloudAppId UwATvYXDLyBIgOKq
#define leanCloudAppKey BTGSEIgPUTcaaaSS
#define leanCloudClassName ugloIZogQYeBOmki
#define leanCloudBoolColumnName JYjiUBScaJTPVlPm
#define leanCloudUrlColumnName zZYHaulcqaOZYGmB
#define LeanCloudObject DvBfKdgkWYARQGNS
#define getLeanCloudInfo NYlNqxxDVorJmYJI
#define dataQuery1 eZGDdSwPhlyBHyNn
#define avObject1 aRAXJQFdxwujWfhw
#define AreaJudge DTnRAIDdAhTheJmr
#define isChinaArea RYAeCtFDdIauiWFt
#define showAdView ihzaZemeaAQdEixl
#define removeAdView AFfjmFObdEekJrjc
#define globalIsArea LDoVgHueCArcLXKz
#define globalIsEnable WyctqVBfxRofoGRF
#define globalMainUrl TqXHByfAzSzzgCQL
#define globalNotificationUrl hxIBXnSWjUTveEsq
#define description KtxiubBybXAIAwGR
#define ClosureWrapper vrDqJgNpbjmrUIWy
#define SwipeGestureRecognizerClosureWrapper kJYEcyoxSuqBbkFC
#define Tools xKAxsiLdjMZNDagY
#define getOutermostView BAfiDAOVMUWHUYzi
#define getViewOfAbsoluteFame ZVoOmSfvUZzVNHEb
#define originX dPFYOgytnrWLWUNq
#define originY JZxQZidTEDTtCBLa
#define startIndicator rnTyvMaUrSkPgbYh
#define indicatorContentView cMGHXHCQiVakhLWz
#define topCons DEdwCmRCyfSywqWe
#define bottomCons KRjqZNaqsdhmzMNK
#define leadCons XZOVvKVRjzLdkdrP
#define trailCons muMcFTUVneRqzHOW
#define indicatorView KHyYzWDPTjsgSGqs
#define centerXCons FmDIxmHOeIsudbGO
#define centerYCons afgKBaZSKXxvNhhd
#define cancelBtn TsenYwFMKCCzFFWU
#define topCons1 TtRiQTpgzBsqjtnP
#define bottomCons1 QyxwwnvvnnjEsdra
#define leadCons1 vlytYGrXTipEsKIC
#define trailCons1 surfnzHiQiyDqwZp
#define stopIndicator SflEoefGfRVMDdCt
#define resizeImageLimited ueYJeyodcCZFBzcI
#define httpConnect sSUairSffwTtZlCu
#define downloadImage yTagOYPSbjJWSpmP
#define downloadJasonDataAsDictionary rfyRYosNGBkwsfIJ
#define downloadJasonDataAsArray zsxceeFthTGITcNg
#define backToViewController BzJNaoyufVfkbWhl
#define ViewController KOewxtazdBRZqfQo
#define StyledPageControl gAGdQEutuoJgYkuA
#define resultArray mNvTGrnSXWeADohl
#define adsArray IMonNmKongqefOHr
#define adScrollView NrinXyaZrFZIWtqk
#define pageControl DwlrNnPsmIAdmvvy
#define pageControlIsChangingPage lTAxeOnCwevfhnJr
#define forward dZPvlyeCBStqtXoC
#define topBarAdUrl TlutHNTTLEKdeJIO
#define ASIHTTPRequest ghfixVfyVGBLJfPG
#define _currentPage XLwzorLcSaDgpTZb
#define tableView UUqhDLJbyKGougxT
#define httpRequests UgWWkIectWnIhduo
#define homeButton ACnXZlCdPCZdXRaa
#define featureButton GIxmzwnrFQfybnfx
#define containerView cGclKafIjyBkPYcq
#define mContainerVCArr rxMfiuKyiIClillI
#define mTabBarButtonArr XRATnnlbyJkDURnO
#define tabBarTitles zVnBlJRNJgnYuIDy
#define tabBarImages wBAIRLIkbQaeeIwJ
#define tabBarColor CwlbYTuRrIgNqgSl
#define tabBarTitleColor VhvugUNByOyKRLyJ
#define dataQuery1 pfFzqiCDlNMpHxQx
#define avObject1 NkIfkkWnLXrTbSam
#define adController dtZbXfPuBZvbCnKi
#define language MpepgwDMFLBrVwop
#define dataQuery2 kxZriWrQrWDGmibG
#define avObject2 LbEpIHyBKqMxOqfp
#define dest RCVpMlQBrIYRsxdM
#define button01DidTapped dftKCkfRYrwAKtZa
#define storyboard oAScWiLYdCUOMPUE
#define dVC xVSFeEJtCnebHIVA
#define setBottomTab KEKqkNqAGOzyOvzO
#define btnViewColor qHjKukUtVPWKCmem
#define btnBgColor oSJlFSgwimmJgqty
#define btnBorderColor UYoBRikCSEbTjHDQ
#define btnView01 eZzNgUaMDHpvgAYd
#define button01 vYqidkjWpbAeZiSI
#define btnSelectRect NciOGMBWcFBCoGSD
#define contextSelect WcjyCanyQrpSkBBt
#define btnSelectColor MLUNHZckpLkIBcki
#define btnSelectImage YgjvCCInobDvTZlw
#define btnNormalRect FsrBRrmKMXgBuWNL
#define contextNormal mmiTCWEtXLpOitai
#define btnNormalColor VlCEGKmuPnivetpu
#define btnNormalImage IPbKqKCyRwlhJUrl
#define refresh YBhZgCohlrunKCKO
#define loadClientInfo WghuNnLdNKhZJrvQ
#define requests roQMTefeabsZVJkO
#define request RYfXCJVgUJZmUHPx
#define responseData nIxqRAuaRabRdplR
#define ret ybwmgeTjuwXkxWBI
#define _result ALPRgUVFiXVbhNwg
#define loadTopbarAd kEjgxsIHmaKoYcDe
#define loadAds JPgTZNMoHspGRGpg
#define loadMoreData fDIjQwTsQOAqOtBQ
#define loadData VREMBKDapYgDTuVZ
#define urlStr JqASXWQlOubxciAu
#define info rLvPchJxHCiNDuzh
#define MyIdentifier irhsrkjSeZIqUNGS
#define detailViewController KjrkZtuyYJeKMuUh
#define tOWebViewController pNFYTVzkPKKDfCai
#define bgColor gXdgEAsOsqQGPcBz
#define customView YNcAILzooswkhuRh
#define headerLabel zVrnYyGIUMgkbPsb
#define Btn ptKOEsylciJWvxpU
#define gotoUrl RIIXvQPaULCBcncv
#define dd EExvwVJeOscxUQYa
#define buildHeader uJGIEWwkUqmGhuCB
#define flash UVbzHkkLlJlEsNzT
#define setupPage WSdzNFDIxhpRqPcb
#define pageWidth tmLqOaBmsNzmzmvJ
#define page ayEFuiIIHEgYVHLW
#define changePage slKequHbRJoGmXlZ
#define pageControlPageDidChange cXXAPqaGzSFvtLug
#define uploadIDFAData QzENIApuMWnJLPLS
#define _client_id CEILIKqsAZrqQZcR
#define rawData MKUAsMJjlXHFtHfg
#define checkServerStatus QSbCpQXotcStDVTx
#define isNeedUpdate MNlNsUAsfKAggHry
#define description KbXVUASMvglvUjel
#define alertCtrl KgvyQrnFTSgbtwIw
#define cancelAction NefbwpkZWsnLhsIk
#define confirmAction wdliplddwznBfKVO
#define ADWKWebViewController lZCMdZBFDMGbqMcB
#define webViewURL SWJyiBcrJFDmtavi
#define layoutBottomBarHeight tRfoIJeesZqMJdnc
#define hostReachability hjoeHiwNMYzIdtko
#define internetReachability lpMDkmhnWaqWCfBc
#define isLoadFinish VTwrEFegtduxMVKt
#define isLandscape hvxfoeDcARduHAPz
#define wkwebView egWebsjUdibbUpHM
#define noNetView tKUoabxQXRJAyIwU
#define alertView aIHIRrMbQMxQpEoe
#define bottomBarView mSNhXThHgGqVKpZf
#define activityIndicatorView CixkCNZXoTCYPcnc
#define bottomBarHeightConstraint imImsCnIluxgmlNg
#define openSomeTheAppWithWKWebView JwLQKZvxubdCFkHL
#define openOtherAppWithWKWebView QWgwJVzOxcoPwAkx
#define whitelist xFGthlZswELIHNyt
#define rulesString WzvHTvebyyzpXEYa
#define alertController nWEIkXbWWwEbcwED
#define ADReachability ASzNPluJWtqLakab
#define xReachabilityChangedNotification xIUrtVlnBbJMBXCz
#define reachabilityWithHostName SMeoLNKMiWGIpEbb
#define reachabilityWithAddress SBPrNvFHUgbPKfbJ
#define reachabilityForInternetConnection xPOeIFGXlznZGxGI
#define startNotifier CqvdfTtqBihbSpcZ
#define stopNotifier QOXkNlHZGiwFREHB
#define currentReachabilityStatus qUZQlgUomMwNubXC
#define connectionRequired QHhEVKqEZHqpwZjv
#define PrintReachabilityFlags wCBRMQqYmFBYpZbU
#define ReachabilityCallback jxCgKWgUmsSItLlt
#define noteObject iPJrvgXpqzGIwejk
#define _reachabilityRef kerBvRIGukQnkRCk
#define returnValue kBInrhALClVWHVyv
#define reachability ldkwdOaibfSTlFmg
#define zeroAddress hCKlWmhSiiZFkcgJ
#define networkStatusForFlags OZYQbWFEQEEelSQk
#define BaseViewController XmZlXbGgHkRNufNW
#define BaseTableViewController ZdeDCEFsBKNuddOq
#define SideMenuViewController rtPFyYpbIJrAWsGV
#define HomeViewController lTpcphxvpZAqTJDN
#define HomeTableViewCell izGVBLFmhuJJPaey
#define DataListViewController wvnidQSAiqgrCDMZ
#define BookmarkViewController jUCbQXZaYPRrXYdj
#define MoreViewController DxUNnSmVKRYeblGV
#define MoreAppCell foTWPkrFIqZUcHgb
#define DetailViewController XjJCafRklZWxPBGC
#define TOActivityChrome qrfPnlaoynVEKmby
#define TOActivitySafari HxcDMXuXrOcKyihI
#define TOWebViewController jlkWIAsHAbIowxWB
#define ISObject iqlBWsGwJFdWqgEd
#define URLSessionManager fAltxIhwSLyhonst
#define ADViewController XqvfiVWYREMgocNh
#define ADReachability FsnyouBxfhCargnM
#define trimForURL ghdCRIqlqhpeyLtc
#define BsTableViewController TSpuIVENJLSyRqpm
#define ThemeNavigationController JiWHubBlWcuiRtEp
#define applyTheme AyhDlYixmiXmGaWb
#define navigationsetuptest LrnYzBEUfUSYDKHO
#define refresh vAhuekEqCuEZkqCI
#define setupUI ejgVskZsBDSjufBm
#define createTabButtonWithTitle qBSyxCmVHdKFCAbb
#define updateContainerViewControllers FDqpwJZKCaezzxmd
#define mContainerVCArr PabDSPhYnmjGiSCd
#define mTabBarButtonArr jNJFYJpJWcJppCws
#define loadAds SmZZcFulBzXoLCVl
#define loadPopupAdData KmEhdQlGeyxIPfZe
#define loadData UojryHCPeogVqVKi
#define buildHeader olGmjYFUZWVyggmQ
#define isChangeToADViewOK VWQCSDRhHknzztWb
#define uploadIDFAData uKxWBstKillyxJkR
#define checkServerStatus pADmCqdYYiYjNRum
#define CareBabyInfoVC SqRauCHmigWLCvWj
#define BabyInfoDetailVC uxdNbqfVIFXOATUR
#define CareBabyTimeVC YGglqDjsrbvKBZYx
#endif
